# Generated by Django 5.2.6 on 2025-09-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomId', models.AutoField(primary_key=True, serialize=False)),
                ('RoomName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='AttendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('JOINED', 'ATTENDING'), ('NOT JOINED', 'NOT ATTENDING')], default='JOINED', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('EventTitle', models.CharField(max_length=120)),
                ('DateOfEvent', models.DateField()),
                ('MaxParticipants', models.IntegerField()),
                ('attendees', models.ManyToManyField(through='CreateEvent.AttendEvent', to='account.student')),
                ('teacher', models.ManyToManyField(to='account.teacher')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateEvent.room')),
            ],
        ),
        migrations.AddField(
            model_name='attendevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateEvent.event'),
        ),
    ]
